---
title: "My Growth as a Data Scientist"
format: html
editor: visual
---

I believe I have improved as a practitioner and student of data science immensely this quarter, as this course allowed me to connect abstract statistical concepts I learned previously in STAT 312 that I didn\'t fully understand with the realm of programming and computer science where I had more experience and proficiency. Doing things such as creating nice looking data visualizations with ggplot graphs and fancy HTML tables gave me an appreciation for the processes of statistical analysis used to gather that data and output it in an easily digestible format, making communication with those outside the realms of technical and mathematical fields more engaging and interesting. Like many other skills in programming, I found that once I learned the basic foundational skills such as filtering, mutating, and summarizing data in pipelines, fitting that data into the proper plot and styling it in a easily readable way a much more engaging experience compared to doing the hard math of Statistical Methods for Engineers, which was my first, and I now find myself trying to decode the elements of visualizations I encounter in day to day life, wondering if it was made in ggplot, whether it be online on reddit or an in-class presentation, as well as being much more appreciative of well-thought out and readable graphs, tables, and plots.
