---
title: "The Power of Efficiency"
format: html
editor: visual
---

In the realm of computing, I believe efficiency lies in the pursuit of finding the simplest means of solving a problem. There are near endless ways to solve a problem in programming thanks to the vast amount of tools available in modern languages and IDE\'s, however I have found that utilizing basic foundational concepts such as iteration, creating and reusing functions, and using proper data structures key to creating manageable and readable codebases. Thankfully in the statistical realm, R and it\'s modern tools such as dplyr and the tidyverse integrate these concepts in spades, which made it very easy to create short and simple solutions that were easy to understand and execute after reading the documentation for a lot of functions. I found A-ha moments when I understood concepts such as pipelines, and doing complex operations in one mutate, filter or summarize function call such as in WD-4, and PE-1. Creating functions of my own such as in PE-2 was also intuitive and I found the ability to perform such large operations on data sets in such little code very powerful.
