---
title: "Lightening Round Essays"
format: html
editor: visual
---

If Bora doesn\'t get an A, then nobody should, because I noticed she was quite active in the discord server, answering lots of questions and asking some, and her code was quite neat when I reviewed it; however, I don\'t have much more info to go off of. The most difficult part of the class for me was having the lab assignment assigned on Thursday and due on Sunday, as when I eventually got around to doing it, it had been quite some time after I had learned and digested the information from the documentation. The easiest part of the class for me was the programming concepts, as they were second nature to me after implementing them for so long. The part of class that surprised and interested me the most was creating plots and visualizations, as after working with abstract data like numbers and variables for so long, I found visualizing and simplifying data immensely rewarding. For a student just starting STAT331, I recommend doing a bit of studying for the class every day; the amount needed depends on the amount of programming experience, but I found that the more I reused concepts, the easier it was to integrate them in implementations to solve problems rather than learning everything at once.
