---
title: "Preview 4: 2 & 3"
author: "Carson Freedman"
format: 
  html:
    self-contained: true
    code-tools: true
execute:
  echo: true
editor: visual
---

```{r}
library(tidyverse)
```

```{r setup}
prof_info <- tibble(
  professor = c("Bodwin", 
                "Glanz", 
                "Carlton",
                "Robinson",
                "Theobold"),
  undergrad_school = c("Harvard", 
                       "Cal Poly",
                       "Berkeley",
                       "Winona State University",
                       "Colorado Mesa University"),
  grad_school = c("UNC", 
                  "Boston University", 
                  "UCLA",
                  "University of Nebraska-Lincoln",
                  "Montana State University")
)

prof_course <- tibble(
  professor = c("Bodwin", "Glanz", "Robinson", "Theobold"),
  Stat_331 = c(TRUE, TRUE, TRUE, TRUE),
  Stat_330 = c(FALSE, TRUE, TRUE, FALSE),
  Stat_431 = c(TRUE, TRUE, TRUE, TRUE)
)

course_info <- data.frame(
  course = c("Stat_331", "Stat_330", "Stat_431"),
  num_sections = c(8, 3, 1)
)
```

```{r}
inner_join(prof_info, prof_course)
```

```{r}
library(liver)
```

```{r}
full_join(prof_info, prof_course)
```
